# Generated by Django 5.1.1 on 2025-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchlist',
            name='accounts_watchlist_user_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
