# Generated by Django 5.1.1 on 2025-12-08 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('kakao', '카카오 알림톡')], max_length=20, verbose_name='채널')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시간')),
                ('success', models.BooleanField(default=False, verbose_name='성공 여부')),
                ('response_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='응답 코드')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='응답 본문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
