# Generated by Django 5.1.1 on 2025-11-27 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_code', models.CharField(help_text='예: KRW-BTC', max_length=20, unique=True, verbose_name='마켓 코드')),
                ('korean_name', models.CharField(max_length=100, verbose_name='한글명')),
                ('english_name', models.CharField(max_length=100, verbose_name='영문명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '암호화폐 코인',
                'verbose_name_plural': '암호화폐 코인 목록',
                'db_table': 'crypto_coin',
                'ordering': ['market_code'],
            },
        ),
        migrations.CreateModel(
            name='CoinCollectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='설정명')),
                ('candle_type', models.CharField(choices=[('days', '일봉'), ('minutes', '분봉'), ('weeks', '주봉'), ('months', '월봉')], default='days', help_text='일봉, 분봉, 주봉, 월봉 중 선택', max_length=20, verbose_name='캔들 타입')),
                ('collection_interval', models.CharField(choices=[('daily', '매일'), ('weekly', '매주'), ('monthly', '매월')], default='daily', help_text='데이터 수집 주기', max_length=20, verbose_name='수집 주기')),
                ('period_days', models.IntegerField(default=30, help_text='한번에 수집할 일 수 (1~200)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='수집 기간(일)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('coins', models.ManyToManyField(related_name='collection_configs', to='crypto.coin', verbose_name='수집 대상 코인')),
            ],
            options={
                'verbose_name': '암호화폐 수집 설정',
                'verbose_name_plural': '암호화폐 수집 설정 목록',
                'db_table': 'crypto_coin_collection_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='거래일')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='저가')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='종가')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='거래량(코인)')),
                ('candle_acc_trade_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='누적 거래대금(KRW)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='crypto.coin', verbose_name='코인')),
            ],
            options={
                'verbose_name': '암호화폐 캔들',
                'verbose_name_plural': '암호화폐 캔들 데이터',
                'db_table': 'crypto_coin_candle',
                'ordering': ['-trade_date'],
                'indexes': [models.Index(fields=['coin', '-trade_date'], name='crypto_coin_coin_id_09ff5c_idx')],
                'unique_together': {('coin', 'trade_date')},
            },
        ),
    ]
