# Generated by Django 5.1.1 on 2025-12-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coincandle',
            name='crypto_coin_coin_id_09ff5c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coincandle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coincandle',
            name='candle_type',
            field=models.CharField(choices=[('days', '일봉'), ('weeks', '주봉'), ('months', '월봉')], db_index=True, default='days', max_length=10, verbose_name='캔들 타입'),
        ),
        migrations.AlterUniqueTogether(
            name='coincandle',
            unique_together={('coin', 'candle_type', 'trade_date')},
        ),
        migrations.AddIndex(
            model_name='coincandle',
            index=models.Index(fields=['coin', 'candle_type', '-trade_date'], name='crypto_coin_coin_id_c43a1a_idx'),
        ),
    ]
