# Generated by Django 5.1.1 on 2025-12-08 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('market', models.CharField(blank=True, max_length=20, null=True, verbose_name='시장')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='섹터')),
                ('listed_at', models.DateField(blank=True, null=True, verbose_name='상장일')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='거래일')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='전일 대비')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='등락률(%)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-trade_date'],
                'unique_together': {('stock', 'trade_date')},
            },
        ),
    ]
