# Generated by Django 5.1.1 on 2025-12-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='거래일(월의 마지막 거래일)')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='전월 대비')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='등락률(%)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='거래일(주의 마지막 거래일)')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='전주 대비')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='등락률(%)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='YearlyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='거래일(연의 마지막 거래일)')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='전년 대비')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='등락률(%)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='dailyprice',
            name='stocks_daily_trade_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyprice',
            name='stocks_daily_stock_date_idx',
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='시장'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='종목명'),
        ),
        migrations.AddField(
            model_name='monthlyprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_prices', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='weeklyprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_prices', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='yearlyprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_prices', to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='monthlyprice',
            index=models.Index(fields=['stock', '-trade_date'], name='stocks_mont_stock_i_fa0b38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyprice',
            unique_together={('stock', 'trade_date')},
        ),
        migrations.AddIndex(
            model_name='weeklyprice',
            index=models.Index(fields=['stock', '-trade_date'], name='stocks_week_stock_i_194cc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprice',
            unique_together={('stock', 'trade_date')},
        ),
        migrations.AddIndex(
            model_name='yearlyprice',
            index=models.Index(fields=['stock', '-trade_date'], name='stocks_year_stock_i_f2d450_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyprice',
            unique_together={('stock', 'trade_date')},
        ),
    ]
